namespace Game1
{
    public static class DefaultItemOptions
    {
        public static string GetOptionName(int id)
        {
            if (id >= 0 && id < Names.Length && !string.IsNullOrEmpty(Names[id]))
            {
                return Names[id];
            }
            return string.Empty;
        }

        public static ItemOptionTemplate CreateTemplate(int id)
        {
            string name = GetOptionName(id);
            if (!string.IsNullOrEmpty(name))
            {
                ItemOptionTemplate t = new ItemOptionTemplate();
                t.id = id;
                t.name = name;
                return t;
            }
            return null;
        }

        public static ItemOptionTemplate[] CreateAllTemplates()
        {
            ItemOptionTemplate[] list = new ItemOptionTemplate[Names.Length];
            for (int i = 0; i < Names.Length; i++)
            {
                list[i] = new ItemOptionTemplate
                {
                    id = i,
                    name = Names[i]
                };
            }
            return list;
        }

        public static readonly string[] Names = new string[]
        {
            /* 0 */ "Tấn công+#",
            /* 1 */ "Thời gian sử dụng # phút",
            /* 2 */ "HP, KI+#000",
            /* 3 */ "Vô hiệu và biến #% sát thương chưởng thành KI",
            /* 4 */ "Hồi phục #% KI khi bị đánh",
            /* 5 */ "+#% sức đánh chí mạng",
            /* 6 */ "HP+#",
            /* 7 */ "KI+#",
            /* 8 */ "Hút #% HP, KI xung quanh mỗi 5 giây",
            /* 9 */ "Hiệu lực trong # phút",
            /* 10 */ "Chính xác: +#",
            /* 11 */ "Công đức +#",
            /* 12 */ "Số lần sử dụng còn lại +#",
            /* 13 */ "Số yêu quái đã hạ +#",
            /* 14 */ "Chí mạng+#%",
            /* 15 */ "Phản đòn cận chiến+#",
            /* 16 */ "Tốc độ di chuyển+#%",
            /* 17 */ "Né đòn: +#",
            /* 18 */ "Chính xác: +#%",
            /* 19 */ "Tấn công+#% khi đánh quái",
            /* 20 */ "PIN #",
            /* 21 */ "Yêu cầu sức mạnh # tỉ",
            /* 22 */ "HP+#K",
            /* 23 */ "KI+#K",
            /* 24 */ "Làm tăng trọng lực, gây chậm mọi người xung quanh",
            /* 25 */ "Tàng hình mỗi 5 giây",
            /* 26 */ "Hóa đá mọi người xung quanh mỗi 30 giây",
            /* 27 */ "+# HP/30s",
            /* 28 */ "+# KI/30s",
            /* 29 */ "Biến Sôcôla mọi người xung quanh mỗi 30 giây",
            /* 30 */ "Không thể giao dịch",
            /* 31 */ "Số lượng #",
            /* 32 */ "Không bị hóa Xương",
            /* 33 */ "Dịch chuyển tức thời",
            /* 34 */ "Tinh ấn",
            /* 35 */ "Nguyệt ấn",
            /* 36 */ "Nhật ấn",
            /* 37 */ "Số lần đã ký gửi #",
            /* 38 */ "Chỉ có tác dụng khi hợp thể",
            /* 39 */ "<Cập nhật bản mới để xem>",
            /* 40 */ "Siêu cải trang # đá ngũ sắc",
            /* 41 */ "(+16)",
            /* 42 */ "(+16)",
            /* 43 */ "(+16)",
            /* 44 */ "(+16)",
            /* 45 */ "(+16)",
            /* 46 */ "(+16)",
            /* 47 */ "Giáp+#",
            /* 48 */ "HP, KI+#",
            /* 49 */ "Tấn công+#%",
            /* 50 */ "Sức đánh+#%",
            /* 51 */ "Sôn Gô Ku ss#",
            /* 52 */ "Ca Đic siêu ss#",
            /* 53 */ "Broly",
            /* 54 */ "Mr. Santa",
            /* 55 */ "Broly ss#",
            /* 56 */ "Ca Lích",
            /* 57 */ "Thên Xin Hăng",
            /* 58 */ "Pic",
            /* 59 */ "Siêu na mếc #",
            /* 60 */ "Sôn Gô Tên",
            /* 61 */ "Sôn Gô Ku",
            /* 62 */ "Phục hồi thể lực #%",
            /* 63 */ "Còn lại # ngày",
            /* 64 */ "Còn lại # giờ",
            /* 65 */ "Còn lại # phút",
            /* 66 */ "Chưa có",
            /* 67 */ "Dùng nâng cấp găng tay",
            /* 68 */ "Dùng để nâng cấp áo",
            /* 69 */ "Dùng để nâng cấp quần",
            /* 70 */ "Dùng để nâng cấp giày",
            /* 71 */ "Dùng để nâng cấp rađa",
            /* 72 */ "Cấp #",
            /* 73 */ "",
            /* 74 */ "Dùng để ép thành đá",
            /* 75 */ "Dùng để làm phép",
            /* 76 */ "Vip",
            /* 77 */ "HP+#%",
            /* 78 */ "Sức hủy diệt+#%",
            /* 79 */ "Đệ tử #% sức đánh",
            /* 80 */ "HP+#%/30s",
            /* 81 */ "KI+#%/30s",
            /* 82 */ "Không bị quái chủ động đánh và giảm 20% sát thương khi bị đánh",
            /* 83 */ "Tăng 20% sức mạnh và tiềm năng nhận được khi đánh quái",
            /* 84 */ "Dùng để bay không tốn KI",
            /* 85 */ "Dùng để bay và phục hồi KI",
            /* 86 */ "Ký gửi vàng",
            /* 87 */ "Ký gửi ngọc",
            /* 88 */ "Cộng #% exp khi đánh quái",
            /* 89 */ "Dùng để bay và phục hồi HP, KI",
            /* 90 */ "Tặng cho người khác (bỏ ra đất) sẽ được nhận may mắn",
            /* 91 */ "Mở ra để nhận may mắn",
            /* 92 */ "Chúc tết bang hội và mọi người kèm theo pháo hoa",
            /* 93 */ "HSD # ngày",
            /* 94 */ "Giáp #%",
            /* 95 */ "Biến #% tấn công thành HP",
            /* 96 */ "Biến #% tấn công thành KI",
            /* 97 */ "Phản #% sát thương",
            /* 98 */ "Xuyên giáp #% chưởng",
            /* 99 */ "Xuyên giáp #% cận chiến",
            /* 100 */ "+#% vàng từ quái",
            /* 101 */ "+#% TN,SM",
            /* 102 */ "# Sao Pha Lê",
            /* 103 */ "KI +#%",
            /* 104 */ "Biến #% tấn công quái thành HP",
            /* 105 */ "Vô hình khi không đánh quái và boss",
            /* 106 */ "Không ảnh hưởng bởi cái lạnh",
            /* 107 */ "# Sao Pha Lê (Chưa ép)",
            /* 108 */ "#% Né đòn",
            /* 109 */ "Hôi, giảm #% HP",
            /* 110 */ "Dò pha lê",
            /* 111 */ "Phân tâm",
            /* 112 */ "Giảm #% khi mua Avatar hoặc Cải trang",
            /* 113 */ "Ném cho Sói Hẹc Quyn",
            /* 114 */ "+#% TĐ chạy",
            /* 115 */ "Biến cà rốt",
            /* 116 */ "Kháng TDHS",
            /* 117 */ "Đẹp +#% SĐ cho mình và người xung quanh",
            /* 118 */ "Tới ngay mục tiêu và gây choáng trong # mili giây",
            /* 119 */ "Gây mù xung quanh trong # giây",
            /* 120 */ "Ra đòn sau # giây",
            /* 121 */ "Ru ngủ trong # giây",
            /* 122 */ "Bảo vệ trong # giây",
            /* 123 */ "Trói gô mục tiêu trong # giây",
            /* 124 */ "Tỉnh giấc bị yếu đi -#% sức đánh trong 10 giây",
            /* 125 */ "Tăng và hồi phục #% HP tạm thời cho mình và xung quanh trong 30 giây",
            /* 126 */ "Biến sôcôla làm yếu đi -#% sức đánh trong 30 giây",
            /* 127 */ "Set Thên Xin Hăng",
            /* 128 */ "Set Kirin",
            /* 129 */ "Set Sôngôku",
            /* 130 */ "Set Picolo",
            /* 131 */ "Set Ốc tiêu",
            /* 132 */ "Set Pikkoro Daimao",
            /* 133 */ "Set Kakarot",
            /* 134 */ "Set Ca Đíc",
            /* 135 */ "Set Nappa",
            /* 136 */ "$(5 món +100% sát thương đấm Galick)",
            /* 137 */ "$(5 món x3 thời gian hóa khỉ)",
            /* 138 */ "$(5 món +80% HP)",
            /* 139 */ "$(5 món x2 thời gian chói mắt)",
            /* 140 */ "$(5 món +100% sát thương Quả Cầu Kênh Khi)",
            /* 141 */ "$(5 món 100% sát thương Kamejoko)",
            /* 142 */ "$(5 món +100% KI)",
            /* 143 */ "$(5 món 100% sát thương Liên hoàn)",
            /* 144 */ "$(5 món +100% sát thương Đẻ Trứng)",
            /* 145 */ "$(Ở gần 1 CT Dr Slum khác loại +20% sức đánh +66% tốc độ chạy)",
            /* 146 */ "$(Ở gần 2 CT Dr Slum khác loại +30% sức đánh +100% tốc độ chạy)",
            /* 147 */ "+#% sức đánh",
            /* 148 */ "+#% tốc độ chạy",
            /* 149 */ "(Chỉ số tăng khi ở gần CT Hải Tặc khác loại)",
            /* 150 */ "(Chỉ số tăng khi ở gần Android Sát Thủ khác loại)",
            /* 151 */ "$(Ở gần 1 CT nhóm Piláp khác loại +20% sức đánh +66% tốc độ chạy)",
            /* 152 */ "$(Ở gần 2 CT nhóm Piláp khác loại +30% sức đánh +100% tốc độ chạy)",
            /* 153 */ "#% tỉ lệ phát nổ sau khi chết",
            /* 154 */ "Không thể bán lại",
            /* 155 */ "Giảm 50% sức đánh, HP, KI và +#% SM, TN, vàng từ quái",
            /* 156 */ "Cộng dồn 1% sức đánh khi chỉ dùng chiêu đấm, tối đa #%",
            /* 157 */ "Giảm #% sát thương",
            /* 158 */ "Khi ở trần và không đeo cải trang sẽ có cơ hội tìm thấy vật phẩm sự kiện",
            /* 159 */ "x# sức đánh đòn chưởng cơ bản mỗi phút",
            /* 160 */ "+#% TN, SM cho đệ tử khi sư phụ mặc cải trang này",
            /* 161 */ "Thêm # ngọc mỗi ngày khi đánh quái.",
            /* 162 */ "Cute hồi #% KI/s bản thân và xung quanh",
            /* 163 */ "Biến người xung quanh thành Bí Ngô",
            /* 164 */ "Đổi bằng # điểm sự kiện",
            /* 165 */ "Cơ hội ra đòn +#% sát thương lửa khi cận chiến quái",
            /* 166 */ "Ngầu +#% sức đánh lên quái khi bay với Cải Trang Tàu Pảy Pảy",
            /* 167 */ "Tạo không khí lạnh",
            /* 168 */ "Hấp thụ sức mạnh rồi bộc phá",
            /* 169 */ "Cơ hội hạ độc đối thủ",
            /* 170 */ "Ngầu +#% sức đánh lên quái khi bay với Cải Trang nhà Fide",
            /* 171 */ "Số lượng #K",
            /* 172 */ "#",
            /* 173 */ "Phục hồi #% HP và KI cho đồng đội",
            /* 174 */ "Sự kiện năm #",
            /* 175 */ "Giảm #% thời gian bị mù",
            /* 176 */ "$(Ở gần đủ 5 loại +20% sức đánh +50% tốc độ chạy)",
            /* 177 */ "$(Tối đa +2% tất cả khi ở gần Mabư mập)",
            /* 178 */ "KI+#%/10s",
            /* 179 */ "+2% sức đánh, tối đa 10% khi ở gần Cải Trang tộc Demons Frost",
            /* 180 */ "+#% sức đánh khi ở gần Cải Trang Black Gohan Rose",
            /* 181 */ "Dịch chuyển tức thời +#% sát thương",
            /* 182 */ "+#% sát thương đệ từ trứng",
            /* 183 */ "Giảm #% thời gian hồi Khiên",
            /* 184 */ "+#% sức đánh, tối đa 10% khi ở gần Gohan xanh, Poc đỏ, Arale búp bê",
            /* 185 */ "+# giờ sử dụng",
            /* 186 */ "Biến mọi người xung quanh thành kẹo mỗi 30 giây",
            /* 187 */ "Giảm # giây thời gian bị mù",
            /* 188 */ "",
            /* 189 */ "",
            /* 190 */ "",
            /* 191 */ "",
            /* 192 */ "SET WORLDCUP",
            /* 193 */ "$(Tăng 10%HP,KI và 20% sức đánh chí mạng khi mặc 2 món WORLDCUP)",
            /* 194 */ "",
            /* 195 */ "",
            /* 196 */ "",
            /* 197 */ "",
            /* 198 */ "+#% TN,SM",
            /* 199 */ "",
            /* 200 */ "",
            /* 201 */ "",
            /* 202 */ "",
            /* 203 */ "",
            /* 204 */ "",
            /* 205 */ "",
            /* 206 */ "",
            /* 207 */ "Cải Trang Sự Kiện",
            /* 208 */ "Đồ rơi từ Quái",
            /* 209 */ "Đồ rơi từ Boss",
            /* 210 */ "Set Tokuda Shigeo",
            /* 211 */ "Set NRO Xưa",
            /* 212 */ "$(5 món thành trùm server)",
            /* 213 */ "Pha lê hóa bị xịt # lần",
            /* 214 */ "Set Kaioken",
            /* 215 */ "$(5 món +100% sát thương Kaioken)",
            /* 216 */ "$(5 món +20% chỉ số bản thân, -50% chỉ số mọi người xung quanh)",
            /* 217 */ "Nhận thêm ngẫu nhiên 0->#% toàn bộ chỉ số.",
            /* 218 */ "Set Bry",
            /* 219 */ "$(5 món trở thành giang hồ mõm)",
            /* 220 */ "$(Vật Phẩm Từ Shop Đặc Cầu)",
            /* 221 */ "Số lần nâng cấp còn lại: #",
            /* 222 */ "+#% sức đánh, tối đa 11% khi ở gần Cải trang cầu thủ khác",
            /* 223 */ "+#% TN, SM cho đệ tử khi sư phụ mặc ",
            /* 224 */ "Chưa giám định",
            /* 225 */ "Số lần tẩy #",
            /* 226 */ "Độ bền #/1000",
            /* 227 */ "Thời hạn hoặc Vĩnh viễn",
            /* 228 */ "Hoàn Thành #%",
            /* 229 */ "+#% May mắn",
            /* 230 */ "Cường Hóa Tới Ô Sao Pha Lê 8\n\n-------",
            /* 231 */ "+20% sát thương Tự phát nổ",
            /* 232 */ "+30% sát thương Makankosappo",
            /* 233 */ "Cute +#% SĐ cho mình và người xung quanh",
            /* 234 */ "Set Nail chiến binh Namếc",
            /* 235 */ "$[2] Tăng nhẹ sát thương chí mạng",
            /* 236 */ "$[4] Giảm nhẹ hồi chiêu Masenko",
            /* 237 */ "$[5] Tăng sát thương Masenko, giảm mạnh hồi chiêu Masenko",
            /* 238 */ "Set Cađic M",
            /* 239 */ "$[2] Tăng nhẹ HP và phạm vi ảnh hưởng chiêu phát nổ",
            /* 240 */ "$[4] Tăng nhẹ sát thương chiêu phát nổ",
            /* 241 */ "$[5] Tăng mạnh sát thương chiêu phát nổ",
            /* 242 */ "Set Thần Vũ Trụ Kaio",
            /* 243 */ "$[2] Tăng mạnh chí mạng",
            /* 244 */ "$[4] Giảm nhẹ hao HP,KI chiêu Kaioken",
            /* 245 */ "$[5] Tăng mạnh sát thương và giảm mạnh hao HP,KI chiêu Kaioken",
            /* 246 */ "Set Kaioken"
        };
    }
}
